PDBBIND:
    # Path to PDBbind index directory
    INDEX: /mnt/scratch/boxiang/projects/pdbbind/v2018/index

PDB:
    # Chemical component coordinate data file downloaded from http://ligand-expo.rcsb.org/ld-download.html
    COORDINATE: /mnt/storage/idl-0/bio/boxiang/cpi_contact/data/Components-pub.sdf
    # Mol_dict saved in pickle format:
    MOL_DICT: /mnt/storage/idl-0/bio/boxiang/cpi_contact/data/mol_dict

DATA:
    # Working directory
    WD: /mnt/storage/idl-0/bio/boxiang/cpi_contact/data/results/
    # Preprocessed data:
    PREPROCESSED: /mnt/storage/idl-0/bio/boxiang/cpi_contact/data/preprocessed/
    # Path to PDB files:
    PDB: /mnt/storage/idl-0/bio/boxiang/cpi_contact/data/pdb_files/
    # Path to PLIP results:
    PLIP: /mnt/storage/idl-0/bio/boxiang/cpi_contact/data/plip_results/
    # Path to MSA:
    MSA: /mnt/storage/idl-0/bio/boxiang/cpi_contact/data/MSA/
    # Path to MSA features:
    MSA_FEATURES: /mnt/storage/idl-0/bio/boxiang/cpi_contact/processed_data/MSA_features/
    # Path to AF2 features:
    AF2: /mnt/storage/idl-0/bio/boxiang/cpi_contact/processed_data/AF2/
SRC:
    # Path to Smith-Waterman alignment source code
    SW: /mnt/storage/idl-0/bio/boxiang/cpi_contact/scripts/dataset/smith-waterman-src/

HHBLITS:
    # Path to HHBlits database
    DATABASE: /mnt/home/vincent/protein_folding/data/UniRef30_2020_02

SLURM:
    QUEUE: TitanXx8,TitanXx8_mlong,TitanXx8_slong,M40x8_slong,M40x8_mlong,M40x8,P100,1080Ti,2080Ti_mlong,2080Ti,CPUx40

