PDBBIND:
    # Path to PDBbind index directory
    INDEX: /mnt/scratch/boxiang/projects/pdbbind/v2018/index

PDB:
    # Chemical component coordinate data file downloaded from http://ligand-expo.rcsb.org/ld-download.html
    COORDINATE: /mnt/scratch/boxiang/projects/cpi_contact/data/Components-pub.sdf

DATA:
    # Working directory
    WD: /mnt/scratch/boxiang/projects/cpi_contact/data/results/
    # Path to PDB files:
    PDB: /mnt/scratch/boxiang/projects/cpi_contact/data/pdb_files/
    # Path to PLIP results:
    PLIP: /mnt/scratch/boxiang/projects/cpi_contact/data/plip_results/
    # Path to MSA:
    MSA: /mnt/scratch/boxiang/projects/cpi_contact/processed_data/MSA/
SRC:
    # Path to Smith-Waterman alignment source code
    SW: /mnt/scratch/boxiang/projects/cpi_contact/scripts/dataset/smith-waterman-src/