PDBBIND:
    # Path to PDBbind index directory
    INDEX: /mnt/scratch/boxiang/projects/pdbbind/v2018/index

PDB:
    # Chemical component coordinate data file downloaded from http://ligand-expo.rcsb.org/ld-download.html
    COORDINATE: /mnt/scratch/boxiang/projects/cpi_contact/data/Components-pub.sdf

DATA:
    # Working directory
    WD: /mnt/scratch/boxiang/projects/cpi_contact/data/results/
    # Path to PDB files:
    PDB: /mnt/scratch/boxiang/projects/cpi_contact/data/pdb_files/
    # Path to PLIP results:
    PLIP: /mnt/scratch/boxiang/projects/cpi_contact/data/plip_results/
    # Path to MSA:
    MSA: /mnt/scratch/boxiang/projects/cpi_contact/data/MSA/

SRC:
    # Path to Smith-Waterman alignment source code
    SW: /mnt/scratch/boxiang/projects/cpi_contact/scripts/dataset/smith-waterman-src/

HHBLITS:
    # Path to HHBlits database
    DATABASE: /mnt/home/vincent/protein_folding/data/UniRef30_2020_02

SLURM:
    QUEUE: TitanXx8,TitanXx8_mlong,TitanXx8_slong,M40x8_slong,M40x8_mlong,M40x8,P100,1080Ti,2080Ti_mlong,2080Ti,CPUx40