PDBBIND:
    # Path to PDBbind index directory
    INDEX: /mnt/scratch/boxiang/projects/pdbbind/v2018/index

DATA:
    # Working directory
    WD: /mnt/scratch/boxiang/projects/cpi_contact/data/
    # Path to PDB files:
    PDB: /mnt/scratch/boxiang/projects/cpi_contact/data/pdb_files/
